//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveBalance
    {
        public decimal Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public Nullable<int> Taken { get; set; }
        public Nullable<int> Balance { get; set; }
        public string Description { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual LeaveType LeaveType { get; set; }
    }
}
